server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: soma-backend
  
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${PGUSER:sa}
    password: ${PGPASSWORD:password}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.soma: DEBUG
    org.springframework.security: DEBUG